config/routes.rb
Rails.application.routes.draw do
  root "articles#index"
  resources :articles
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  include ArticlesHelper
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    # @articles = collect_data_page('https://news.ycombinator.com/best')
     @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :image, :author, :point, :time, :comments, :content, :domain, :link)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
  require 'nokogiri'
  require 'open-uri'
  require 'readability'
  require 'fastimage'

  # This method to get list hash of all newest article
  def collect_data_page(url)
    source = Readability::Document.new(open(url).read).prepare_candidates[:elem] 
    hash_list_article = source.css('a.storylink').each_with_object({}) { |n, h| h[n.text.strip] = n['href'] }
    list_information = source.css('td.subtext').map {|infor| infor.content}

    # This list hash has type: [{}, {}]
    hash_list_article.map.with_index do |value, index|
      link = if value[1].include?("item")
               "https://news.ycombinator.com/" + value[1]
             else
               value[1]
             end
      begin
        article = Readability::Document.new(open(link).read, :tags => %w[div p img a], :attributes => %w[src href])
        image = article.images
        
        { title: value[0],
          link: link,
          image: image == [] ? article.images_with_fqdn_uris(link) : image,
          domain: link.split("//")[1].split("/").first, # Sub string to get right type of domain
          content: article.content,
          infor: list_information[index].strip # Remove many spaces
        }
      rescue
        { title: "",
          link: "",
          image: "",
          domain: "",
          content: "",
          infor: "",
        }
      end      
    end
    
  end

  # This method to create record to save in Database
  def iniitialize_record(url)
    (1..7).each do |index|
      list_artical = collect_data_page(url + "?p="+ index.to_s)
      list_artical.each_with_index do |value, index|
        if value[:title] != ""
          Article.create!(title: value[:title],
                          link: value[:link],
                          image: value[:image].first,
                          domain: value[:domain],
                          content: value[:content],
                          author: value[:infor])
        end
      end
    end
  end
  
end

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :point %>
    <%= form.number_field :point %>
  </div>

  <div class="field">
    <%= form.label :time %>
    <%= form.text_field :time %>
  </div>

  <div class="field">
    <%= form.label :comments %>
    <%= form.number_field :comments %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :domain %>
    <%= form.text_field :domain %>
  </div>

  <div class="field">
    <%= form.label :link %>
    <%= form.text_field :link %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<nav class="navbar navbar-light bg-light" style="z-index: 2;">
    <h1>NEWS</h1>
</nav>
<div class="alert col-off-4 col-12" style='margin: 80px 5% 0 0;'></div>
<ul>
    <% @articles.each do |article| %>
        <li class="booking-card" style="background-image: url('<%= article.image == nil ? 'https://s3-us-west-2.amazonaws.com/s.cdpn.io/74321/fbanijhrol4-annie-spratt-776x951.jpg' : article.image %>')">
            <div class="book-container">
                <div class="content">
                    <%= link_to "#{article.domain }", article_path(article), :class => "btn" %></button>
                </div>
            </div>
            <div class="informations-container">
                <h2 class="title"><%= article.title.slice(0..19) + '...' %></h2>
                <p class="sub-title" style="color: #7d7d7d; font-size: 0.7rem;"><%= article.author %></p>
                <div class="more-information">                    
                    <p class="disclaimer" ><%= raw article.content %></p>
                </div>
            </div>
        </li>
    <% end %>
</ul>
<script>
 if ($('li.booking-card').length < 21) {
     location.reload(true);
 } else if ( $('li.booking-card').length > 20 && $('li.booking-card').length < 150) {
     $('div.alert').append("<div class='alert alert-info' role='alert' >You can reload this page to get more newest.</div>");
 };
</script>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<nav class="navbar navbar-light bg-light" style="z-index: 1;">
    <%= button_to articles_path, class: "btn btn-outline-dark", method: :get do%>
        Back
    <% end %>
</nav>
<figure class="figure col-12" style="text-align: center; padding-top: 50px;">
    <img src="<%= @article.image == nil ? 'https://s3-us-west-2.amazonaws.com/s.cdpn.io/74321/fbanijhrol4-annie-spratt-776x951.jpg' : @article.image %>" class="img-fluid" alt="Responsive image" style="height: 300px;">
    <h1><%= @article.title %></h1>
    <h2><small><%= @article.domain %></small></h6>
    <div style="text-align: left; padding: 0 5%;">
        <%= raw @article.content %>
    </div>
</figure>
<style>
 p{
     padding: 0;
 }
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewsReader</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>